import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppStateProvider, AuthProvider, ProductProvider, CategoryProvider, MatchProvider } from "@/contexts";
import ToastContainer from "@/components/ui/ToastContainer";
import ModalContainer from "@/components/ui/ModalContainer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Reuse Next",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppStateProvider>
          <AuthProvider>
            <CategoryProvider>
              <MatchProvider>
                <ProductProvider>
                  {children}
                  <ToastContainer />
                  <ModalContainer />
                </ProductProvider>
              </MatchProvider>
            </CategoryProvider>
          </AuthProvider>
        </AppStateProvider>
      </body>
    </html>
  );
}
